/**
 * @apsis/db — re-exports the drizzle-kit generated migrations object.
 *
 * Used by apps/mobile's _layout.tsx:
 *   import { db } from '@apsis/db';
 *   import { migrations } from '@apsis/db';
 *   const { success, error } = useMigrations(db, migrations);
 *
 * The generated drizzle/migrations.js imports:
 *   - drizzle/meta/_journal.json  (migration sequence metadata)
 *   - drizzle/0000_*.sql          (schema SQL as inline string via babel-plugin-inline-import)
 *
 * IMPORTANT (RESEARCH Pitfall 5, T-1-04):
 *   - drizzle/migrations.js is auto-generated by drizzle-kit — never hand-edit it
 *   - drizzle/ is append-only; run `npx drizzle-kit generate` after schema changes
 *   - apps/mobile/babel.config.js must have the inline-import plugin for .sql files
 *   - apps/mobile/metro.config.js must include 'sql' in resolver.sourceExts
 *   Both configs were wired in Plan 01-02.
 */

// @ts-ignore — migrations.js is a generated JS file (no .d.ts); skipLibCheck covers this
import migrations from '../drizzle/migrations';

export { migrations };
